# Generated by Django 4.0.4 on 2022-09-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=30)),
                ('curculatingSupply', models.DecimalField(decimal_places=2, max_digits=18)),
                ('priceInUSD', models.DecimalField(decimal_places=2, max_digits=18)),
                ('timeStamp', models.DateTimeField()),
            ],
        ),
    ]
