# Generated by Django 4.0.4 on 2022-09-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='id',
        ),
        migrations.AddField(
            model_name='crypto',
            name='rank',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
