# Generated by Django 4.0.4 on 2022-09-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_crypto_id_crypto_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crypto',
            old_name='rank',
            new_name='id',
        ),
        migrations.AddField(
            model_name='crypto',
            name='cmc_rank',
            field=models.PositiveIntegerField(default=0, null=True, unique=True),
        ),
    ]
